### ISSUE TITLE
Traduire les pages du wiki en français

### ISSUE THREAD

**Issue by nikixiaoyou** [GrisouUQAM/wikiContributions#11]
Quand j'ai créé le dépôt, je l'ai fait pour la gloire éternelle, et ma théorie c'est qu'elle viendrait en anglais. Toutefois, la plupart, si ce n'est pas la totalité des collaborateurs actuels sont francophones.
Il faudrait donc ajouter des pages en français, et faire en sorte que lorsqu'un utilisateur arrive sur notre dépôt, qu'il puisse choisir la langue de son choix dans nos pages wiki.

Je vais faire un squelette des pages pour commencer.

**Comment by nikixiaoyou** [comment]
Après avoir retiré tout ce qui touche WEHA dans notre wiki, il ne reste plus de pages à traduire! Notre wiki est 100% bilingue! :)

**Comment by ialexca** [comment]
Qui maintiendra la version anglaise maintenant? Je propose que l'ont concerve la version française seulement à la racine du Wiki.

**Comment by nikixiaoyou** [comment]
Ça ne me dérange pas de m'occuper de la version anglaise, il n'y a pas
souvent des changements à notre wiki. Au pire, si ça devient difficile à
gérer, on enlèvera la version anglaise. Je l'avais ajouté à la demande de
Louise, parce que nous voulons que notre projet soit ouvert à tous! :)

2013/9/30 Alexandre Poupart notifications@github.com
