### ISSUE TITLE
Timestamps aren't precise enough

### ISSUE THREAD

**Issue by nikixiaoyou** [GrisouUQAM/wikiContributions#2]
At the moment, we extract timestamps from the wiki API and compare them to measure how long a revision has lasted. However, since wiki contributions aren't necessarily whole articles, time between revisions only tell us how long it took before someone added/removed something from an article, no matter what part of the article this person has edited. Therefore, if person A adds an important piece of information to an article concerning binary trees (for example), and 2 days later, person B adds or removes another piece of information from that same article, WITHOUT changing the important piece added by A, our code will tell us that the revision made by person A on the binary trees article lasted 2 days, which might be untrue. A contribution can last months even when the article is revised every week, if none of the revisions apply to this contribution.
We need to change the way we measure the survival of a contribution.

**Comment by GrisouUQAM** [comment]
Voir issue #10
