### ISSUE TITLE
Performance is simply horrible.

### ISSUE THREAD

**Issue by nikixiaoyou** [GrisouUQAM/wikiContributions#3]
Since a JVM is created everytime a call to WEHA is made, performance is horrible. We had to extend the server's execution timeout in order to see the results on our web site, and that's only when looking at a user with 2 contributions to 2 small articles. Alexandre has suggested we use tools on the server side for compatibility with DLL (something that came with newer versions of PHP), but honnestly, I wouldn't know where to start.

There's also a possibility of rewriting the Java portion of the code in a language that doesn't require a virtual machine.

Or, simply using another code for text comparisons!

**Comment by ialexca** [comment]
WEHA n'est plus utilisé.
Nous utilisons Google-Diff-Match-Patch maintenant: https://code.google.com/p/google-diff-match-patch/
