### ISSUE TITLE
Is JavaBridge really necessary?

### ISSUE THREAD

**Issue by nikixiaoyou** [GrisouUQAM/wikiContributions#4]
I haven't had time to look deep into WEHA, but as I see it now, there are no Java files being used for our project to work, and perhaps it could run without JavaBridge. This would make the installation of our project on someone else's computer much easier, and perhaps more people would be interested in contributing to it!

**Comment by nikixiaoyou** [comment]
After having taken a closer look, the file wikiLexer.php is the one using Java, and without it, the project doesn't work properly. It create a StringReader and uses it to analyze the text,

**Comment by ialexca** [comment]
Lors de la réunion des GRISOU du 10 sept, nous avons décidé de retirer la branche WEHA du projet. 

WEHA est spécialisé dans la compilation de texte en "Wikimarkup". Si l'ont veut trouver la différence entre deux contribution en "plain text" par exemple, il sera impossible de le faire avec l'API de WEHA. Dans le cas ou la norme du Wikimarkup change, il faudra recréer la grammaire du compilateur, une compétence que personne a dans l'équipe des GRISOU.

Ensuite, l'API n'implémente aucun algorithme connu pour afficher les différences et similitudes d'un texte. WEHA est peu performant. 

Pour terminer, il n'y a aucune documentation, aucun test fourni avec le code. Modifier un code existant serait une perte de temps. Vaut mieux partir sur une meilleure base.
