### ISSUE TITLE
L'API de wiki ne retourne pas toujours les même résultats

### ISSUE THREAD

**Issue by nikixiaoyou** [GrisouUQAM/wikiContributions#6]
Il semble que lorsqu'on lance une requête pour un utilisateur donné, on n'obtient pas les mêmes textes à tout coup. Je crois que wiki nous retourne peut-être les modifications les plus récentes pour une révision, ou encore, on obtient la même révision, mais si un utilisateur a été banni, ses contributions n'y apparaissent plus.. Il faudrait investiguer!

**Comment by ialexca** [comment]
Pourrais-tu donner un exemple?
Est-ce que le résultat est différent d'un exécution à l'autre, où d'un jour à l'autre?

**Comment by nikixiaoyou** [comment]
Il me semble que c'était d'un jour à l'autre... Dès que je réussis à reproduire le problème, j'enverrai des détails concernant cette issue!

**Comment by nikixiaoyou** [comment]
Problème plus ou moins résolu avec les nouvelles interfaces écrites par les étudiants.
