### ISSUE TITLE
Une page test pour Google-Diff

### ISSUE THREAD

**Issue by nikixiaoyou** [GrisouUQAM/wikiContributions#8]
Puisque WEHA a sa page test dans notre code, nous devrions en faire autant pour Google-Diff, ça faciliterait les comparaisons entre les 2!

**Comment by ialexca** [comment]
Il faudrait faire un effort de trouver une façon d'extraire le texte du code HTML pour avoir des résultat comparatif a WEHA.
Ref:
https://code.google.com/p/google-diff-match-patch/wiki/Plaintext

**Comment by nikixiaoyou** [comment]
C'est fait, et j'ai ajouté la fonction "strip_tags" dans diffFunctions, ce qui retire tous les tags html d'un texte!
