### ISSUE TITLE
Déménager le code

### ISSUE THREAD

**Issue by nikixiaoyou** [GrisouUQAM/wikiContributions#9]
Puisqu'il s'agit d'un dépôt public, il serait facile d'en créer un nouveau au nom de Grisou et de mettre le code à cet endroit. Ça serait un peu plus facile à retenir que "nikixiaoyou" ! :)

**Comment by ialexca** [comment]
Quand penses-tu le faire? Je propose à la fin de ton contrat.

**Comment by nikixiaoyou** [comment]
Je pense le faire la semaine prochaine, qui est en même temps la fin de mon
contrat! :)

Je te tiens au courant..

**Comment by GrisouUQAM** [comment]
Done! :)
